//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AldeaAndreiClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MateriaField;
        
        private int NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Materia {
            get {
                return this.MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MateriaField, value) != true)) {
                    this.MateriaField = value;
                    this.RaisePropertyChanged("Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AldeaAndreiClient.ServiceReference1.HelloWorldResponse HelloWorld(AldeaAndreiClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(AldeaAndreiClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name getStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        AldeaAndreiClient.ServiceReference1.getStudentsResponse getStudents(AldeaAndreiClient.ServiceReference1.getStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentsResponse> getStudentsAsync(AldeaAndreiClient.ServiceReference1.getStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        AldeaAndreiClient.ServiceReference1.addStudentResponse addStudent(AldeaAndreiClient.ServiceReference1.addStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.addStudentResponse> addStudentAsync(AldeaAndreiClient.ServiceReference1.addStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        void deleteStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        System.Threading.Tasks.Task deleteStudentAsync(int id);
        
        // CODEGEN: Generating message contract since element name getStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudent", ReplyAction="*")]
        AldeaAndreiClient.ServiceReference1.getStudentResponse getStudent(AldeaAndreiClient.ServiceReference1.getStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentResponse> getStudentAsync(AldeaAndreiClient.ServiceReference1.getStudentRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editStudent", ReplyAction="*")]
        AldeaAndreiClient.ServiceReference1.editStudentResponse editStudent(AldeaAndreiClient.ServiceReference1.editStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.editStudentResponse> editStudentAsync(AldeaAndreiClient.ServiceReference1.editStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AldeaAndreiClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AldeaAndreiClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudents", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.getStudentsRequestBody Body;
        
        public getStudentsRequest() {
        }
        
        public getStudentsRequest(AldeaAndreiClient.ServiceReference1.getStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getStudentsRequestBody {
        
        public getStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.getStudentsResponseBody Body;
        
        public getStudentsResponse() {
        }
        
        public getStudentsResponse(AldeaAndreiClient.ServiceReference1.getStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AldeaAndreiClient.ServiceReference1.Student[] getStudentsResult;
        
        public getStudentsResponseBody() {
        }
        
        public getStudentsResponseBody(AldeaAndreiClient.ServiceReference1.Student[] getStudentsResult) {
            this.getStudentsResult = getStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudent", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.addStudentRequestBody Body;
        
        public addStudentRequest() {
        }
        
        public addStudentRequest(AldeaAndreiClient.ServiceReference1.addStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string materia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nota;
        
        public addStudentRequestBody() {
        }
        
        public addStudentRequestBody(string name, string materia, int nota) {
            this.name = name;
            this.materia = materia;
            this.nota = nota;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.addStudentResponseBody Body;
        
        public addStudentResponse() {
        }
        
        public addStudentResponse(AldeaAndreiClient.ServiceReference1.addStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addStudentResponseBody {
        
        public addStudentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudent", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.getStudentRequestBody Body;
        
        public getStudentRequest() {
        }
        
        public getStudentRequest(AldeaAndreiClient.ServiceReference1.getStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getStudentRequestBody() {
        }
        
        public getStudentRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.getStudentResponseBody Body;
        
        public getStudentResponse() {
        }
        
        public getStudentResponse(AldeaAndreiClient.ServiceReference1.getStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AldeaAndreiClient.ServiceReference1.Student getStudentResult;
        
        public getStudentResponseBody() {
        }
        
        public getStudentResponseBody(AldeaAndreiClient.ServiceReference1.Student getStudentResult) {
            this.getStudentResult = getStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editStudent", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.editStudentRequestBody Body;
        
        public editStudentRequest() {
        }
        
        public editStudentRequest(AldeaAndreiClient.ServiceReference1.editStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string materia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int nota;
        
        public editStudentRequestBody() {
        }
        
        public editStudentRequestBody(int id, string name, string materia, int nota) {
            this.id = id;
            this.name = name;
            this.materia = materia;
            this.nota = nota;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public AldeaAndreiClient.ServiceReference1.editStudentResponseBody Body;
        
        public editStudentResponse() {
        }
        
        public editStudentResponse(AldeaAndreiClient.ServiceReference1.editStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class editStudentResponseBody {
        
        public editStudentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AldeaAndreiClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AldeaAndreiClient.ServiceReference1.WebService1Soap>, AldeaAndreiClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AldeaAndreiClient.ServiceReference1.HelloWorldResponse AldeaAndreiClient.ServiceReference1.WebService1Soap.HelloWorld(AldeaAndreiClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AldeaAndreiClient.ServiceReference1.HelloWorldRequest inValue = new AldeaAndreiClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.HelloWorldRequestBody();
            AldeaAndreiClient.ServiceReference1.HelloWorldResponse retVal = ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.HelloWorldResponse> AldeaAndreiClient.ServiceReference1.WebService1Soap.HelloWorldAsync(AldeaAndreiClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            AldeaAndreiClient.ServiceReference1.HelloWorldRequest inValue = new AldeaAndreiClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.HelloWorldRequestBody();
            return ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AldeaAndreiClient.ServiceReference1.getStudentsResponse AldeaAndreiClient.ServiceReference1.WebService1Soap.getStudents(AldeaAndreiClient.ServiceReference1.getStudentsRequest request) {
            return base.Channel.getStudents(request);
        }
        
        public AldeaAndreiClient.ServiceReference1.Student[] getStudents() {
            AldeaAndreiClient.ServiceReference1.getStudentsRequest inValue = new AldeaAndreiClient.ServiceReference1.getStudentsRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.getStudentsRequestBody();
            AldeaAndreiClient.ServiceReference1.getStudentsResponse retVal = ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).getStudents(inValue);
            return retVal.Body.getStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentsResponse> AldeaAndreiClient.ServiceReference1.WebService1Soap.getStudentsAsync(AldeaAndreiClient.ServiceReference1.getStudentsRequest request) {
            return base.Channel.getStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentsResponse> getStudentsAsync() {
            AldeaAndreiClient.ServiceReference1.getStudentsRequest inValue = new AldeaAndreiClient.ServiceReference1.getStudentsRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.getStudentsRequestBody();
            return ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).getStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AldeaAndreiClient.ServiceReference1.addStudentResponse AldeaAndreiClient.ServiceReference1.WebService1Soap.addStudent(AldeaAndreiClient.ServiceReference1.addStudentRequest request) {
            return base.Channel.addStudent(request);
        }
        
        public void addStudent(string name, string materia, int nota) {
            AldeaAndreiClient.ServiceReference1.addStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.addStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.addStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.materia = materia;
            inValue.Body.nota = nota;
            AldeaAndreiClient.ServiceReference1.addStudentResponse retVal = ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).addStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.addStudentResponse> AldeaAndreiClient.ServiceReference1.WebService1Soap.addStudentAsync(AldeaAndreiClient.ServiceReference1.addStudentRequest request) {
            return base.Channel.addStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.addStudentResponse> addStudentAsync(string name, string materia, int nota) {
            AldeaAndreiClient.ServiceReference1.addStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.addStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.addStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.materia = materia;
            inValue.Body.nota = nota;
            return ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).addStudentAsync(inValue);
        }
        
        public void deleteStudent(int id) {
            base.Channel.deleteStudent(id);
        }
        
        public System.Threading.Tasks.Task deleteStudentAsync(int id) {
            return base.Channel.deleteStudentAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AldeaAndreiClient.ServiceReference1.getStudentResponse AldeaAndreiClient.ServiceReference1.WebService1Soap.getStudent(AldeaAndreiClient.ServiceReference1.getStudentRequest request) {
            return base.Channel.getStudent(request);
        }
        
        public AldeaAndreiClient.ServiceReference1.Student getStudent(int id) {
            AldeaAndreiClient.ServiceReference1.getStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.getStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.getStudentRequestBody();
            inValue.Body.id = id;
            AldeaAndreiClient.ServiceReference1.getStudentResponse retVal = ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).getStudent(inValue);
            return retVal.Body.getStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentResponse> AldeaAndreiClient.ServiceReference1.WebService1Soap.getStudentAsync(AldeaAndreiClient.ServiceReference1.getStudentRequest request) {
            return base.Channel.getStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.getStudentResponse> getStudentAsync(int id) {
            AldeaAndreiClient.ServiceReference1.getStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.getStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.getStudentRequestBody();
            inValue.Body.id = id;
            return ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).getStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AldeaAndreiClient.ServiceReference1.editStudentResponse AldeaAndreiClient.ServiceReference1.WebService1Soap.editStudent(AldeaAndreiClient.ServiceReference1.editStudentRequest request) {
            return base.Channel.editStudent(request);
        }
        
        public void editStudent(int id, string name, string materia, int nota) {
            AldeaAndreiClient.ServiceReference1.editStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.editStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.editStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.materia = materia;
            inValue.Body.nota = nota;
            AldeaAndreiClient.ServiceReference1.editStudentResponse retVal = ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).editStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.editStudentResponse> AldeaAndreiClient.ServiceReference1.WebService1Soap.editStudentAsync(AldeaAndreiClient.ServiceReference1.editStudentRequest request) {
            return base.Channel.editStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AldeaAndreiClient.ServiceReference1.editStudentResponse> editStudentAsync(int id, string name, string materia, int nota) {
            AldeaAndreiClient.ServiceReference1.editStudentRequest inValue = new AldeaAndreiClient.ServiceReference1.editStudentRequest();
            inValue.Body = new AldeaAndreiClient.ServiceReference1.editStudentRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.materia = materia;
            inValue.Body.nota = nota;
            return ((AldeaAndreiClient.ServiceReference1.WebService1Soap)(this)).editStudentAsync(inValue);
        }
    }
}
